### ISSUE TITLE
Strange Bash Syntax Highlighting

### ISSUE THREAD

**Issue by jonleopard** [dracula/prism#2]
Hello, 

First off, thanks for making a prism port for the Dracula theme!

My site uses [Gatsby](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/), which is a static site generator that uses React under the hood. What I have done so far is copy the contents of `dracula-prism.css` and put inside my markdown.js component (I am using styled components, so css-in-js). You can see what I've done here:
https://github.com/jonleopard/jonleopard.com/blob/master/src/components/markdown.js#L93

The syntax seems a little off inside of the bash code blocks:
https://www.jonleopard.com/dotfile-management-with-gnu-stow/

The `inline code` do not seem to have a background color.
https://www.jonleopard.com/upgrading-ghost-inside-docker/

I think I have implemented everything correctly, but I was wondering what your thoughts are on the strange bash syntax highlighting, as well as the inline color issue.

Thanks again for making this !

**Comment by gusbemacbe** [comment]
Hello, thank you for reporting the issue, I have analysed.

* My JS Prismjs doesn't have line highlight plugin as Gatsby indicates, so I will enable all JS plugins to update the CSS . 
* As you used `code` which dosn't have a background-color, change the background-color:

```css
:not(pre) > code[class*="language-"],
pre[class*="language-"] 
{
	background: #f5f2f0;
}

/* Inline code */
:not(pre) > code[class*="language-"] 
{
	padding: .1em;
	border-radius: .3em;
	white-space: normal;
}
```

Change `#f5f2f0` to `rgb(40, 41, 54)` and tell me if it got good or bad.

Then I will analyse the CSS and update the CSS.
